swagger: '2.0'
info:
  version: '1.0'
  title: quasar LoanPrograms
  contact: {}
host: quasarloanprograms.us-west-2.elasticbeanstalk.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /v1/loanprograms:
    get:
      summary: GetLoadProgramsByTenantIdAndClientId
      tags:
      - LoanPrograms v1
      operationId: GetLoadProgramsByTenantIdAndClientId
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: clientId
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      - name: tenantId
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/GetLoadProgramsByTenantIdAndClientId'
          examples:
            application/json:
              rowCount: 3
              data:
              - ProgramId: 2
                ProgramName: Loan Program 2.1
                ProgramType: ''
                BaseRate: ''
                RateChangeFrequency: ''
                InterestAccrualMethod: ''
                IsActive: 0
              - ProgramId: 4
                ProgramName: Loan Program 4
                ProgramType: ''
                BaseRate: ''
                RateChangeFrequency: ''
                InterestAccrualMethod: ''
                IsActive: 0
              - ProgramId: 6
                ProgramName: Rustic Granite Pizza 6.1
                ProgramType: ''
                BaseRate: ''
                RateChangeFrequency: ''
                InterestAccrualMethod: ''
                IsActive: 1
              statusDescription: OK
              statusCode: 200
          headers:
            connection:
              type: string
              default: keep-alive
            content-encoding:
              type: string
              default: gzip
            content-length:
              type: string
              default: '212'
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Mon, 18 Sep 2017 21:55:34 GMT
            etag:
              type: string
              default: W/"212-ePTlCSn71q1O/WzYdbAeNkMYdUs"
            server:
              type: string
              default: nginx/1.10.2
            x-powered-by:
              type: string
              default: Express
    post:
      summary: PostLoadProgramsByTenantIdAndClientId
      tags:
      - LoanPrograms v1
      operationId: PostLoadProgramsByTenantIdAndClientId
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: clientId
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      - name: tenantId
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/PostLoadProgramsByTenantIdAndClientIdRequest'
      responses:
        '200':
          description: ''
          headers: {}
  /v1/loanprograms/6:
    put:
      summary: PutLoadProgramsByTenantIdAndClientId
      tags:
      - LoanPrograms v1
      operationId: PutLoadProgramsByTenantIdAndClientId
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: clientId
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      - name: tenantId
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/PutLoadProgramsByTenantIdAndClientIdRequest'
      responses:
        '200':
          description: ''
          headers: {}
    delete:
      summary: DeleteLoadProgramsByTenantIdAndClientId
      tags:
      - LoanPrograms v1
      operationId: DeleteLoadProgramsByTenantIdAndClientId
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: clientId
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      - name: tenantId
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/DeleteLoadProgramsByTenantIdAndClientIdRequest'
      responses:
        '200':
          description: ''
          headers: {}
  /v1/loanprograms/2:
    patch:
      summary: PatchLoadProgramsByTenantIdAndClientId
      tags:
      - LoanPrograms v1
      operationId: PatchLoadProgramsByTenantIdAndClientId
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: clientId
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      - name: tenantId
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/PatchLoadProgramsByTenantIdAndClientIdRequest'
      responses:
        '200':
          description: ''
          headers: {}
  /v1/loanprogramtemplates:
    get:
      description: Get All Loan Program Templates
      summary: Get All Loan Program Templates
      tags:
      - Loan Programs Template v1
      operationId: GetAllLoanProgramTemplates
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/GetAllLoanProgramTemplates'
          examples:
            application/json:
              data:
              - CreatedDate: 2017-09-15
                Settings:
                  PaymentApplication:
                    Order: Fees/Interest/Principal
                    AllowPaidAhead: No
                  ReduceTerm:
                    Statuses:
                    - Status: Repayment
                    - Status: MilitaryRepayment
                    - Status: Bankruptcy
                    - Status: Claim
                    - Status: HardshipForbearance
                  Fees:
                    NSF:
                      PercentOrDollar: Amount
                      Minimum: 0
                      Maximum: 0
                      Amount: 20
                    Late:
                      PercentOrDollar: Percent
                      Minimum: 0
                      Maximum: 9999.99
                      DaysLate: 15
                      Statuses:
                      - Status: Repayment
                      - Status: Bankruptcy
                      - Status: Claim
                      Amount: 5
                  InterestAccrual:
                    Statuses:
                    - Status: Repayment
                      AutoPayIncentive: 0.25
                    - Status: MilitaryRepayment
                      AutoPayIncentive: 0.25
                      MaxRate: 6
                    - Status: Bankruptcy
                    - Status: Claim
                    - Status: Default
                    - Status: HardshipForbearance
                    - Status: DisasterForbearance
                    Frequency: Monthly
                    Method: Actual/Actual
                  Billing:
                    Statuses:
                    - Status: Repayment
                    - Status: MilitaryRepayment
                    - Status: HardshipForbearance
                    - Status: DisasterForbearance
                    Frequency: Monthly
                    Days: 21
                UpdatedDate: 2017-9-15
                TemplateName: KristinTest2
                Version: '1.0'
                IsActive: true
                Description: This is an updated template for Kristin
                Id: KristinTest
              - UpdatedDate: 2017-09-15 10:25:19.147
                CreatedDate: 2017-09-15 10:25:19.147
                Settings:
                  PaymentApplication:
                    Order: Fees/Interest/Principal
                    AllowPaidAhead: No
                  ReduceTerm:
                    Statuses:
                    - Status: Repayment
                    - Status: MilitaryRepayment
                    - Status: Bankruptcy
                    - Status: Claim
                    - Status: HardshipForbearance
                  Fees:
                    NSF:
                      PercentOrDollar: Amount
                      Minimum: 0
                      Maximum: 0
                      Amount: 20
                    Late:
                      PercentOrDollar: Percent
                      Minimum: 0
                      Maximum: 9999.99
                      DaysLate: 15
                      Statuses:
                      - Status: Repayment
                      - Status: Bankruptcy
                      - Status: Claim
                      Amount: 5
                  InterestAccrual:
                    Statuses:
                    - Status: Repayment
                      AutoPayIncentive: 0.25
                    - Status: MilitaryRepayment
                      MaxRate: 6
                      AutoPayIncentive: 0.25
                    - Status: Bankruptcy
                    - Status: Claim
                    - Status: Default
                    - Status: HardshipForbearance
                    - Status: DisasterForbearance
                    Frequency: Monthly
                    Method: Actual/Actual
                  Billing:
                    Statuses:
                    - Status: Repayment
                    - Status: MilitaryRepayment
                    - Status: HardshipForbearance
                    - Status: DisasterForbearance
                    Frequency: Monthly
                    Days: 21
                Version: '1.0'
                TemplateName: BasePersonalFixed
                IsActive: true
                Description: BasePersonalFixed
                Id: 9d90a944-438a-4763-9d25-f60ec33bf4f3
              - UpdatedDate: 2017-09-15 10:28:19.147
                CreatedDate: 2017-09-15 10:28:19.147
                Settings:
                  PaymentApplication:
                    Order: Fees/Interest/Principal
                    AllowPaidAhead: No
                  ReduceTerm:
                    Statuses:
                    - Status: Repayment
                    - Status: MilitaryRepayment
                    - Status: Bankruptcy
                    - Status: Claim
                    - Status: HardshipForbearance
                  Fees:
                    NSF:
                      PercentOrDollar: Amount
                      Minimum: 0
                      Maximum: 0
                      Amount: 20
                    Late:
                      PercentOrDollar: Percent
                      Minimum: 0
                      Maximum: 9999.99
                      DaysLate: 15
                      Statuses:
                      - Status: Repayment
                      - Status: Bankruptcy
                      - Status: Claim
                      Amount: 5
                  InterestAccrual:
                    Statuses:
                    - Status: Repayment
                      AutoPayIncentive: 0.25
                    - Status: MilitaryRepayment
                      MaxRate: 6
                      AutoPayIncentive: 0.25
                    - Status: Bankruptcy
                    - Status: Claim
                    - Status: Default
                    - Status: HardshipForbearance
                    - Status: DisasterForbearance
                    Frequency: Monthly
                    Method: Actual/Actual
                  Billing:
                    Statuses:
                    - Status: Repayment
                    - Status: MilitaryRepayment
                    - Status: HardshipForbearance
                    - Status: DisasterForbearance
                    Frequency: Monthly
                    Days: 21
                Version: '1.0'
                TemplateName: BasePersonal Variable
                IsActive: true
                Description: BasePersonalFixed
                Id: 8db8875c-3396-4c64-baac-e4a77436b9c8
              statusDescription: OK
              statusCode: 200
          headers:
            content-encoding:
              type: string
              default: gzip
            content-length:
              type: string
              default: '681'
            content-type:
              type: string
              default: application/json; charset=utf-8
            date:
              type: string
              default: Mon, 18 Sep 2017 22:04:18 GMT
            etag:
              type: string
              default: W/"e7c-vUPOBXXej+UKhOmIGuWRGXaQQVA"
            server:
              type: string
              default: nginx/1.10.2
            x-powered-by:
              type: string
              default: Express
  /v1/loanprogramtemplates/BasePersonal Variable1:
    get:
      description: Get All Loan Program Templates by Template Name
      summary: Get All Loan Program Templates by Template Name
      tags:
      - Loan Programs Template v1
      operationId: GetAllLoanProgramTemplatesbyTemplateName
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
  /v2/loanprograms:
    get:
      description: Get Client Specific Templates
      summary: Get Client Specific Templates
      tags:
      - Loan Program v2
      operationId: GetClientSpecificTemplates
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: tenantid
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      - name: clientid
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      responses:
        '200':
          description: ''
          headers: {}
  /v2/loanprograms/BasePersonalFixed:
    get:
      description: Get Client Specific Templates by Template Name
      summary: Get Client Specific Templates by Template Name
      tags:
      - Loan Program v2
      operationId: GetClientSpecificTemplatesbyTemplateName
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: tenantid
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      - name: clientid
        in: header
        required: true
        type: integer
        format: int32
        description: ''
      responses:
        '200':
          description: ''
          headers: {}
definitions:
  GetLoadProgramsByTenantIdAndClientId:
    title: GetLoadProgramsByTenantIdAndClientId
    example:
      rowCount: 3
      data:
      - ProgramId: 2
        ProgramName: Loan Program 2.1
        ProgramType: ''
        BaseRate: ''
        RateChangeFrequency: ''
        InterestAccrualMethod: ''
        IsActive: 0
      - ProgramId: 4
        ProgramName: Loan Program 4
        ProgramType: ''
        BaseRate: ''
        RateChangeFrequency: ''
        InterestAccrualMethod: ''
        IsActive: 0
      - ProgramId: 6
        ProgramName: Rustic Granite Pizza 6.1
        ProgramType: ''
        BaseRate: ''
        RateChangeFrequency: ''
        InterestAccrualMethod: ''
        IsActive: 1
      statusDescription: OK
      statusCode: 200
    type: object
    properties:
      rowCount:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/Datum'
      statusDescription:
        type: string
      statusCode:
        type: integer
        format: int32
    required:
    - rowCount
    - data
    - statusDescription
    - statusCode
  Datum:
    title: Datum
    example:
      ProgramId: 2
      ProgramName: Loan Program 2.1
      ProgramType: ''
      BaseRate: ''
      RateChangeFrequency: ''
      InterestAccrualMethod: ''
      IsActive: 0
    type: object
    properties:
      ProgramId:
        type: integer
        format: int32
      ProgramName:
        type: string
      ProgramType:
        type: string
      BaseRate:
        type: string
      RateChangeFrequency:
        type: string
      InterestAccrualMethod:
        type: string
      IsActive:
        type: integer
        format: int32
    required:
    - ProgramId
    - ProgramName
    - ProgramType
    - BaseRate
    - RateChangeFrequency
    - InterestAccrualMethod
    - IsActive
  PostLoadProgramsByTenantIdAndClientIdRequest:
    title: PostLoadProgramsByTenantIdAndClientIdRequest
    example:
      programId: 6
      programName: Rustic Granite Pizza 6
      isActive: 1
    type: object
    properties:
      programId:
        type: integer
        format: int32
      programName:
        type: string
      isActive:
        type: integer
        format: int32
    required:
    - programId
    - programName
    - isActive
  PutLoadProgramsByTenantIdAndClientIdRequest:
    title: PutLoadProgramsByTenantIdAndClientIdRequest
    example:
      programId: 6
      programName: Rustic Granite Pizza 6.1
      isActive: 1
    type: object
    properties:
      programId:
        type: integer
        format: int32
      programName:
        type: string
      isActive:
        type: integer
        format: int32
    required:
    - programId
    - programName
    - isActive
  DeleteLoadProgramsByTenantIdAndClientIdRequest:
    title: DeleteLoadProgramsByTenantIdAndClientIdRequest
    example:
      programId: '2'
      programName: Loan Program 2
    type: object
    properties:
      programId:
        type: string
      programName:
        type: string
    required:
    - programId
    - programName
  PatchLoadProgramsByTenantIdAndClientIdRequest:
    title: PatchLoadProgramsByTenantIdAndClientIdRequest
    example:
      programName: Loan Program 2.1
    type: object
    properties:
      programName:
        type: string
    required:
    - programName
  GetAllLoanProgramTemplates:
    title: GetAllLoanProgramTemplates
    example:
      data:
      - CreatedDate: 2017-09-15
        Settings:
          PaymentApplication:
            Order: Fees/Interest/Principal
            AllowPaidAhead: No
          ReduceTerm:
            Statuses:
            - Status: Repayment
            - Status: MilitaryRepayment
            - Status: Bankruptcy
            - Status: Claim
            - Status: HardshipForbearance
          Fees:
            NSF:
              PercentOrDollar: Amount
              Minimum: 0
              Maximum: 0
              Amount: 20
            Late:
              PercentOrDollar: Percent
              Minimum: 0
              Maximum: 9999.99
              DaysLate: 15
              Statuses:
              - Status: Repayment
              - Status: Bankruptcy
              - Status: Claim
              Amount: 5
          InterestAccrual:
            Statuses:
            - Status: Repayment
              AutoPayIncentive: 0.25
            - Status: MilitaryRepayment
              AutoPayIncentive: 0.25
              MaxRate: 6
            - Status: Bankruptcy
            - Status: Claim
            - Status: Default
            - Status: HardshipForbearance
            - Status: DisasterForbearance
            Frequency: Monthly
            Method: Actual/Actual
          Billing:
            Statuses:
            - Status: Repayment
            - Status: MilitaryRepayment
            - Status: HardshipForbearance
            - Status: DisasterForbearance
            Frequency: Monthly
            Days: 21
        UpdatedDate: 2017-9-15
        TemplateName: KristinTest2
        Version: '1.0'
        IsActive: true
        Description: This is an updated template for Kristin
        Id: KristinTest
      - UpdatedDate: 2017-09-15 10:25:19.147
        CreatedDate: 2017-09-15 10:25:19.147
        Settings:
          PaymentApplication:
            Order: Fees/Interest/Principal
            AllowPaidAhead: No
          ReduceTerm:
            Statuses:
            - Status: Repayment
            - Status: MilitaryRepayment
            - Status: Bankruptcy
            - Status: Claim
            - Status: HardshipForbearance
          Fees:
            NSF:
              PercentOrDollar: Amount
              Minimum: 0
              Maximum: 0
              Amount: 20
            Late:
              PercentOrDollar: Percent
              Minimum: 0
              Maximum: 9999.99
              DaysLate: 15
              Statuses:
              - Status: Repayment
              - Status: Bankruptcy
              - Status: Claim
              Amount: 5
          InterestAccrual:
            Statuses:
            - Status: Repayment
              AutoPayIncentive: 0.25
            - Status: MilitaryRepayment
              MaxRate: 6
              AutoPayIncentive: 0.25
            - Status: Bankruptcy
            - Status: Claim
            - Status: Default
            - Status: HardshipForbearance
            - Status: DisasterForbearance
            Frequency: Monthly
            Method: Actual/Actual
          Billing:
            Statuses:
            - Status: Repayment
            - Status: MilitaryRepayment
            - Status: HardshipForbearance
            - Status: DisasterForbearance
            Frequency: Monthly
            Days: 21
        Version: '1.0'
        TemplateName: BasePersonalFixed
        IsActive: true
        Description: BasePersonalFixed
        Id: 9d90a944-438a-4763-9d25-f60ec33bf4f3
      - UpdatedDate: 2017-09-15 10:28:19.147
        CreatedDate: 2017-09-15 10:28:19.147
        Settings:
          PaymentApplication:
            Order: Fees/Interest/Principal
            AllowPaidAhead: No
          ReduceTerm:
            Statuses:
            - Status: Repayment
            - Status: MilitaryRepayment
            - Status: Bankruptcy
            - Status: Claim
            - Status: HardshipForbearance
          Fees:
            NSF:
              PercentOrDollar: Amount
              Minimum: 0
              Maximum: 0
              Amount: 20
            Late:
              PercentOrDollar: Percent
              Minimum: 0
              Maximum: 9999.99
              DaysLate: 15
              Statuses:
              - Status: Repayment
              - Status: Bankruptcy
              - Status: Claim
              Amount: 5
          InterestAccrual:
            Statuses:
            - Status: Repayment
              AutoPayIncentive: 0.25
            - Status: MilitaryRepayment
              MaxRate: 6
              AutoPayIncentive: 0.25
            - Status: Bankruptcy
            - Status: Claim
            - Status: Default
            - Status: HardshipForbearance
            - Status: DisasterForbearance
            Frequency: Monthly
            Method: Actual/Actual
          Billing:
            Statuses:
            - Status: Repayment
            - Status: MilitaryRepayment
            - Status: HardshipForbearance
            - Status: DisasterForbearance
            Frequency: Monthly
            Days: 21
        Version: '1.0'
        TemplateName: BasePersonal Variable
        IsActive: true
        Description: BasePersonalFixed
        Id: 8db8875c-3396-4c64-baac-e4a77436b9c8
      statusDescription: OK
      statusCode: 200
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Datum1'
      statusDescription:
        type: string
      statusCode:
        type: integer
        format: int32
    required:
    - data
    - statusDescription
    - statusCode
  Datum1:
    title: Datum1
    example:
      CreatedDate: 2017-09-15
      Settings:
        PaymentApplication:
          Order: Fees/Interest/Principal
          AllowPaidAhead: No
        ReduceTerm:
          Statuses:
          - Status: Repayment
          - Status: MilitaryRepayment
          - Status: Bankruptcy
          - Status: Claim
          - Status: HardshipForbearance
        Fees:
          NSF:
            PercentOrDollar: Amount
            Minimum: 0
            Maximum: 0
            Amount: 20
          Late:
            PercentOrDollar: Percent
            Minimum: 0
            Maximum: 9999.99
            DaysLate: 15
            Statuses:
            - Status: Repayment
            - Status: Bankruptcy
            - Status: Claim
            Amount: 5
        InterestAccrual:
          Statuses:
          - Status: Repayment
            AutoPayIncentive: 0.25
          - Status: MilitaryRepayment
            AutoPayIncentive: 0.25
            MaxRate: 6
          - Status: Bankruptcy
          - Status: Claim
          - Status: Default
          - Status: HardshipForbearance
          - Status: DisasterForbearance
          Frequency: Monthly
          Method: Actual/Actual
        Billing:
          Statuses:
          - Status: Repayment
          - Status: MilitaryRepayment
          - Status: HardshipForbearance
          - Status: DisasterForbearance
          Frequency: Monthly
          Days: 21
      UpdatedDate: 2017-9-15
      TemplateName: KristinTest2
      Version: '1.0'
      IsActive: true
      Description: This is an updated template for Kristin
      Id: KristinTest
    type: object
    properties:
      CreatedDate:
        type: string
      Settings:
        $ref: '#/definitions/Settings'
      UpdatedDate:
        type: string
      TemplateName:
        type: string
      Version:
        type: string
      IsActive:
        type: boolean
      Description:
        type: string
      Id:
        type: string
    required:
    - CreatedDate
    - Settings
    - UpdatedDate
    - TemplateName
    - Version
    - IsActive
    - Description
    - Id
  Settings:
    title: Settings
    example:
      PaymentApplication:
        Order: Fees/Interest/Principal
        AllowPaidAhead: No
      ReduceTerm:
        Statuses:
        - Status: Repayment
        - Status: MilitaryRepayment
        - Status: Bankruptcy
        - Status: Claim
        - Status: HardshipForbearance
      Fees:
        NSF:
          PercentOrDollar: Amount
          Minimum: 0
          Maximum: 0
          Amount: 20
        Late:
          PercentOrDollar: Percent
          Minimum: 0
          Maximum: 9999.99
          DaysLate: 15
          Statuses:
          - Status: Repayment
          - Status: Bankruptcy
          - Status: Claim
          Amount: 5
      InterestAccrual:
        Statuses:
        - Status: Repayment
          AutoPayIncentive: 0.25
        - Status: MilitaryRepayment
          AutoPayIncentive: 0.25
          MaxRate: 6
        - Status: Bankruptcy
        - Status: Claim
        - Status: Default
        - Status: HardshipForbearance
        - Status: DisasterForbearance
        Frequency: Monthly
        Method: Actual/Actual
      Billing:
        Statuses:
        - Status: Repayment
        - Status: MilitaryRepayment
        - Status: HardshipForbearance
        - Status: DisasterForbearance
        Frequency: Monthly
        Days: 21
    type: object
    properties:
      PaymentApplication:
        $ref: '#/definitions/PaymentApplication'
      ReduceTerm:
        $ref: '#/definitions/ReduceTerm'
      Fees:
        $ref: '#/definitions/Fees'
      InterestAccrual:
        $ref: '#/definitions/InterestAccrual'
      Billing:
        $ref: '#/definitions/Billing'
    required:
    - PaymentApplication
    - ReduceTerm
    - Fees
    - InterestAccrual
    - Billing
  PaymentApplication:
    title: PaymentApplication
    example:
      Order: Fees/Interest/Principal
      AllowPaidAhead: No
    type: object
    properties:
      Order:
        type: string
      AllowPaidAhead:
        type: string
    required:
    - Order
    - AllowPaidAhead
  ReduceTerm:
    title: ReduceTerm
    example:
      Statuses:
      - Status: Repayment
      - Status: MilitaryRepayment
      - Status: Bankruptcy
      - Status: Claim
      - Status: HardshipForbearance
    type: object
    properties:
      Statuses:
        type: array
        items:
          $ref: '#/definitions/Status'
    required:
    - Statuses
  Status:
    title: Status
    example:
      Status: Repayment
    type: object
    properties:
      Status:
        type: string
    required:
    - Status
  Fees:
    title: Fees
    example:
      NSF:
        PercentOrDollar: Amount
        Minimum: 0
        Maximum: 0
        Amount: 20
      Late:
        PercentOrDollar: Percent
        Minimum: 0
        Maximum: 9999.99
        DaysLate: 15
        Statuses:
        - Status: Repayment
        - Status: Bankruptcy
        - Status: Claim
        Amount: 5
    type: object
    properties:
      NSF:
        $ref: '#/definitions/NSF'
      Late:
        $ref: '#/definitions/Late'
    required:
    - NSF
    - Late
  NSF:
    title: NSF
    example:
      PercentOrDollar: Amount
      Minimum: 0
      Maximum: 0
      Amount: 20
    type: object
    properties:
      PercentOrDollar:
        type: string
      Minimum:
        type: integer
        format: int32
      Maximum:
        type: integer
        format: int32
      Amount:
        type: integer
        format: int32
    required:
    - PercentOrDollar
    - Minimum
    - Maximum
    - Amount
  Late:
    title: Late
    example:
      PercentOrDollar: Percent
      Minimum: 0
      Maximum: 9999.99
      DaysLate: 15
      Statuses:
      - Status: Repayment
      - Status: Bankruptcy
      - Status: Claim
      Amount: 5
    type: object
    properties:
      PercentOrDollar:
        type: string
      Minimum:
        type: integer
        format: int32
      Maximum:
        type: number
        format: double
      DaysLate:
        type: integer
        format: int32
      Statuses:
        type: array
        items:
          $ref: '#/definitions/Status'
      Amount:
        type: integer
        format: int32
    required:
    - PercentOrDollar
    - Minimum
    - Maximum
    - DaysLate
    - Statuses
    - Amount
  InterestAccrual:
    title: InterestAccrual
    example:
      Statuses:
      - Status: Repayment
        AutoPayIncentive: 0.25
      - Status: MilitaryRepayment
        AutoPayIncentive: 0.25
        MaxRate: 6
      - Status: Bankruptcy
      - Status: Claim
      - Status: Default
      - Status: HardshipForbearance
      - Status: DisasterForbearance
      Frequency: Monthly
      Method: Actual/Actual
    type: object
    properties:
      Statuses:
        type: array
        items:
          $ref: '#/definitions/Status2'
      Frequency:
        type: string
      Method:
        type: string
    required:
    - Statuses
    - Frequency
    - Method
  Status2:
    title: Status2
    example:
      Status: Repayment
      AutoPayIncentive: 0.25
    type: object
    properties:
      Status:
        type: string
      AutoPayIncentive:
        type: number
        format: double
      MaxRate:
        type: integer
        format: int32
    required:
    - Status
  Billing:
    title: Billing
    example:
      Statuses:
      - Status: Repayment
      - Status: MilitaryRepayment
      - Status: HardshipForbearance
      - Status: DisasterForbearance
      Frequency: Monthly
      Days: 21
    type: object
    properties:
      Statuses:
        type: array
        items:
          $ref: '#/definitions/Status'
      Frequency:
        type: string
      Days:
        type: integer
        format: int32
    required:
    - Statuses
    - Frequency
    - Days
tags:
- name: LoanPrograms v1
- name: Loan Programs Template v1
- name: Loan Program v2
